### ISSUE TITLE
Compose not working 

### ISSUE THREAD

**Issue by Fastidious** [cheeaun/phanpy#22]
Compose doesn’t do anything under mobile Safari.

**Comment by Fastidious** [comment]
It is, actually, not working on Safari on desktop either. At least, not for me.

**Comment by Fastidious** [comment]
OK, you can close this, because it seems to be related to my Fediverse instance, rather than Phanpy. I am using GoToSocial, which implements Mastodon APIs. It seems the way this client interacts is not compatible with anything else, but Mastodon. Pinafore works with GTS, but that client approach is different from the one Phanpy uses.

Leaving it for the developer to close, in case something is needed from me, or if there is interest in supporting GoToSocial.

**Comment by cheeaun** [comment]
@Fastidious I'll need more details on specific things that are not working 🙏 

I could try register an account on a GTS instance for testing, but I will be **more focused** on Mastodon (latest version) for now (I don't have the capacity to test all other fediverse variants 🙇‍♂️). If GTS's API is the same as Mastodon, it should be fine, else could be a bug in GTS instead? 🤔

**Comment by Fastidious** [comment]
@cheeaun I will bring this to the GTS team. They are on holidays, so please if you could leave this open till early next year it will be much appreciated.

**Comment by Alex0007** [comment]
Compose not doing for me either. Pop-up is not appearing

Google Chrome on Pixel 6. 

On Firefox it's working though

**Comment by cheeaun** [comment]
@Alex0007 which instance do you use? Do you mean it works on Firefox browser on Pixel 6?

**Comment by Alex0007** [comment]
@cheeaun personally i don't think it is depending on instance. I'm using `mstdn.social`

Yes, Firefox on Pixel 6 is working

**Comment by Fastidious** [comment]
Ever since switching to my own Mastodon instance I haven’t been able to replicate this (iOS Safari/Chrome, and macOS Safari/Chrome). This isn’t an issue for me anymore. Leaving the issue open as it seems relevant to someone else.

**Comment by cheeaun** [comment]
@Alex0007 can you check again? Might need you to clear cache 🙏

**Comment by Alex0007** [comment]
@cheeaun it is now showing an alert with text:

Failed to load instance configuration. Please try again.

**Comment by cheeaun** [comment]
@Alex0007 okay, try refresh again 😀

**Comment by Alex0007** [comment]
@cheeaun i see no new commits since last try. Just tried again and the error is still there

<details>
  <summary>Screenshot</summary>
  
![telegram-cloud-photo-size-2-5287425326781156270-y](https://user-images.githubusercontent.com/1143226/209772623-91c0a437-b913-4b5d-a8b4-0e333439bcfd.jpg)
  
</details>

**Comment by cheeaun** [comment]
@Alex0007 oh that's odd. Try:

1. Close and re-open the web page. See if the error is there. If it's still there… go to (2)
2. Clear cache for the site, re-login/authenticate. Check for the error again.

Thanks! 🙏

**Comment by Alex0007** [comment]
@cheeaun still the same. I've tried within incognito mode

**Comment by cheeaun** [comment]
@Alex0007 I just tried in incognito mode on Chrome Android on Pixel 3, works for me 😅 My Chrome version is 108.0.5359.128, on Android 12 (I can't upgrade to 13 because Pixel 3 is no longer supported 😭).

Few checks:
- Are you using dev.phanpy.social?
- Are there any specific settings in the browser that could possibly cause the issue?

Thanks! 🙏

**Comment by Alex0007** [comment]
@cheeaun i guess i've found the issue:

`mstdn.social` is missing on the list of instances, so i'm typing it. But Google keyboard makes first character to be uppercase, so i typed `Mstdn.social`

This caused the issue. If i switch case and type `mstdn.social`, then compose starts to work

**Comment by cheeaun** [comment]
@Alex0007 thanks a lot! Wow this bug is hard to find 😆 Ok, I'll do these:

1. Disable `autocapitalize` on the input field
2. Lowercase the domain string in the code before saving/using it.
3. Extra step, I'll refresh the list. I don't know why `mstdn.social` is not in the list since the last time I run the fetch script. I'll also bump up the number of instances in the list.

**Comment by Alex0007** [comment]
It was never in that list for me. I guess because registration is closed there
