### ISSUE TITLE
Auto-scrolling posts into view with keyboard j/k nav

### ISSUE THREAD

**Issue by johnsonm** [cheeaun/phanpy#246]
I could keep my fingers on home row instead of bouncing back and forth between j/k and up/down with a little bit of auto-scrolling behavior. ☺

Here, I have used the `j` key to select a post that is fully on the screen:

![Screenshot from 2023-10-02 22-07-22](https://github.com/cheeaun/phanpy/assets/79751/3ef5d7fe-79c8-4742-a5dd-a892d6ed479e)

One more `j` and I have selected a post that is off the screen

![Screenshot from 2023-10-02 22-07-27](https://github.com/cheeaun/phanpy/assets/79751/a99a457f-1696-44f6-9b6e-d3fcc7bbf208)

Similarly, cycling through a boost carousel doesn't pull posts onto the screen sideways.

Here, I have used `j` to move through the carousel to select a recent post about a Phanpy release (:tada:)

![Screenshot from 2023-10-02 22-16-13](https://github.com/cheeaun/phanpy/assets/79751/bb34146a-6719-457a-8da2-7a61e3b2b303)

But then another `j` takes me mostly out of sight:

![Screenshot from 2023-10-02 22-16-17](https://github.com/cheeaun/phanpy/assets/79751/8771b8a2-dcf4-4726-a74b-a80f8aa609e3)

I would love it if selecting a new post with j/k tried to scroll it onto the screen. If the post is larger than the screen, scrolling it so that the top is visible plus as much of the rest of the post fits on the screen would be perfect, I think. Even if it sometimes wasn't perfect, rarely using arrow keys instead of always using arrow keys would be easier.

I'm running Phanpy dev on Firefox 118 on GNOME/Wayland/Linux, Fedora 37 x86_64.

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️

**Comment by johnsonm** [comment]
Yes! It works! Thank you!

**Comment by agenbite** [comment]
I'm grateful for this app, it's sooo much nicer than the default.

Wrt vertical alignment, though, it would be perfect if the newly selected post would display at the top of the screen, instead of at the bottom: being the case that not all toots have the same height, right now you need to visually find where the toot starts in order to start reading. If all the selected toots were top-aligned upon using j/k, your eyes don't need to identify where they start: you just look at the top of the screen to start reading.

In the carusel, this works nicely because the toots are centered in the carrusel (and so their position is always predictable).

**Comment by agenbite** [comment]
I should add that the Catch-up screen does align the toots when scrolling with j/k, except they're aligned in the center of the screen, instead of in the top. This indicates that it shouldn't be so difficult to implement it for the standard timeline?
