### ISSUE TITLE
Fav/Boost buttons cause scroll FPS frops when in field of view

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#26]
Status column scroll is noticeably laggier than scrolling feed (tested on mobile, Firefox and Google Chrome browsers)

Not sure if it is visible on the video example: https://youtu.be/_trWui7Kb1I

UPD.: another example https://youtube.com/shorts/tqtidp7RF7Q (laggy scroll, then normal scroll)

**UPD2**.: it's post like/boost buttons cause scroll lags. When they are on screen – there are a lot of freezes when scrolling

**Comment by Alex0007** [comment]
@cheeaun i guess it's somehow related with boost/fav buttons block. Scroll is performing OK, when this block is not in the field of view

**Comment by cheeaun** [comment]
@Alex0007 thanks, the videos are super useful. I suspect the images are too huge? Honestly I personally find most media files (images and videos) from Mastodon instances are *really* **not** well-compressed and reasonably-resized, which makes this a bit tough.

I'll check this on my side to figure out what other factors affecting the performance 🙏 

Just FYI: you can upload videos here in GitHub issues too! I don't know what's the file size limit but it's easier when the video is part of the issue instead of another website.

**Comment by Alex0007** [comment]
Not sure why you're mentioning media files here, because issue is 100% in the block with buttons. As soon it's not on the screen, all lags disappear

![Screenshot_20230103-120523](https://user-images.githubusercontent.com/1143226/210319667-d5eb98a9-73f2-40be-a773-3b575d18a776.png)


Thank you for video uploading advices!
