### ISSUE TITLE
<esc> should dismiss user/author bottom panel too

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#69]
Otherwise this is a bit odd:

1. Click a Mastodon link
2. Right panel that shows that post and thread appears
3. Click on a post author
4. Bottom panel that shows user appears
5. Hit `<esc>`
6. Right panel disappears, but user bottom panel still remains open

This state in (4):

<img width="1120" alt="Screenshot 2023-02-22 at 9 57 58 AM" src="https://user-images.githubusercontent.com/56189/220501283-bd78747e-5dc5-4cfd-8d6b-074e3f7d61d5.png">

**Comment by hboon** [comment]
Looks fixed on dev.phanpy.social (@cheeaun do you not close issues with the commit message/PRs?)

**Comment by cheeaun** [comment]
Oh cool! Closing.

@hboon I only close when fix is in prod, and only do issues maintenance every few weeks (across all my repos) 😂

**Comment by hboon** [comment]
Ah, makes sense. Thanks.

**Comment by forteller** [comment]
Hi. I noticed that when pressing Esc in this situation both the author panel and the right panel disappears at the same time. For me I think the most intuitive thing would be to only close the most recently opened panel each time you hit Esc, so that first it closes the author panel and then you hit it again to close the right panel. If not you might open the author panel to check out the author of one toot, then intend to go back to reading the rest of the thread, but lose your place in the thread when you hit Esc and both the author panel and the right panel disappears at the same time.

Also: The Alt text bottom panel does not respond to Esc. Is it ok that I just post that here, or do you want it as a separate issue?

Thank you for a really great service!

**Comment by cheeaun** [comment]
@forteller could you create new issues for these? Thanks! 🙇‍♂️
